language: ruby
rvm: 2.5.1
env:
  - DB=mysql
branches:
  only:
    - master
script:
  - "bundle exec rake db:create"
  - "bundle exec rake db:migrate RAILS_ENV=test"
  - "bundle exec rspec spec"
before_script:
  - mysql -e 'create database `library_directory_test`'