version: '3.1'

services:

  elasticsearch:
    image: elasticsearch:6.8.1
    container_name: elasticsearch
    restart: always
    volumes: 
      - ./search_data:/usr/share/elasticsearch/data
    ports: 
      - 9200:9200
      - 9300:9300
   
  db:
    image: mysql:5.7.27
    container_name: database
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-files:/var/lib/mysql-files
  
  rails: 
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    container_name: directory
    environment:
      - DATABASE_PASSWORD=docker
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - TERM=xterm 
      - SELENIUM_REMOTE_HOST=selenium
    #  - RAILS_ENV=production # uncomment if in production
    volumes:
      - ./:/home/directory
    ports:
      - "3000:3000" 
      - "3001:3001"
    links:
      - elasticsearch
      - db
      - selenium # development only
  
  selenium:
    image: selenium/standalone-chrome-debug
    container_name: selenium
    privileged: true
    ports:
      - '4444:4444'
      - '5900:5900'
    environment:
      - SCREEN_WIDTH=1440
      - SCREEN_HEIGHT=900
      - VNC_NO_PASSWORD=true
    logging:
      driver: none