version: '3.1'

services:

  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
    restart: always
    volumes: 
      - ./search_data:/usr/share/elasticsearch/data
    ports: 
      - 9200:9200
      - 9300:9300
   
  db:
    image: mysql:5.7.16
    container_name: database
    restart: always
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ./mysql:/var/lib/mysql
  
  rails: 
    build: 
      context: ./
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    container_name: directory
    restart: always
    # command:
    #   bash -c "RAILS_ENV=test puma -b tcp://0.0.0.0:3001 -d && puma -C config/puma.rb"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - SECRET_KEY_BASE=3eaa9178c5728347e93d431a61061bac6b4d62ffa62840d269168b1250e26364180d65dc91555a47d472f32542e4d7bbc9f4452cb2efbf45c5ac7038194cc02c
      - DATABASE_PASSWORD=docker
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - TERM=xterm 
      - SELENIUM_REMOTE_HOST=selenium
    volumes:
      - ./:/home/directory
    ports:
      - "3000:3000" 
      - "3001:3001"
    links:
      - elasticsearch
      - db
      - selenium
  
  selenium:
    image: selenium/standalone-chrome-debug
    container_name: selenium
    privileged: true
    ports:
      - '4444:4444'
      - '5900:5900'
    environment:
      - SCREEN_WIDTH=1440
      - SCREEN_HEIGHT=900
      - VNC_NO_PASSWORD=true
    logging:
      driver: none